### ISSUE TITLE
Consider name change

### ISSUE THREAD

**Issue by jansobczak** [daniele-athome/roundcube-search-scope#2]
I don't know how to write roundcube plugins but i found out this:

`Failed to load plugin file /var/www/webmail/plugins/roundcube-search-scope/roundcube-search-scope.php in /var/www/webmail/program/lib/Roundcube/rcube_plugin_api.php on line 173 (GET /webmail/?_task=mail&_action=list&_refresh=1&_mbox=INBOX&_remote=1&_unlock=loading1471965995235&_=1471965822497)`

My plugin config before changes:
`$config['plugins'] =  array('emoticons', ...... 'roundcube-search-scope' )`

My quick solution was to change names. Than plugin started working:
- folder from roundcube-search-scope to roundcube_search_scope.
- class php file from search_scope.php to roundcube_search_scope.
- class name from search_scope to roundcube_search_scope.

My plugin config after changes:
`$config['plugins'] =  array('emoticons', ...... 'roundcube_search_scope' )`

**Comment by daniele-athome** [comment]
It is enough to name the cloned directory `search_scope` and use `search_scope` in your configuration. I'll modify the README to state that.

**Comment by jansobczak** [comment]
Oh ok thank u :)

On August 23, 2016 7:03:40 PM GMT+02:00, Daniele Ricci notifications@github.com wrote:

> It is enough to name the cloned directory `search_scope` and use
> `search_scope` in your configuration. I'll modify the README to state
> that.
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/daniele-athome/roundcube-search-scope/issues/2#issuecomment-241802439

## 

Wysłane za pomocą K-9 Mail.
